name = "EquivariantTensors"
uuid = "5e107534-7145-4f8f-b06f-47a52840c895"
version = "0.3.2"

[deps]
ACEbase = "14bae519-eb20-449c-a949-9c58ed33163e"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DecoratedParticles = "023d0394-cb16-4d2d-a5c7-724bed42bbb6"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
MLDataDevices = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
PartialWaveFunctions = "793d2195-304b-438e-bbb1-bc33c872ac39"
Polynomials4ML = "03c4bcba-a943-47e9-bfa1-b1661fc2974f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
WignerD = "87c4ff3e-34df-11e9-37a7-516cea4e0402"
WithAlloc = "fb1aa66a-603c-4c1d-9bc4-66947c7b08dd"

[weakdeps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
AtomsBuilder = "f5cc8831-eeb7-4288-8d9f-d6c1ddb77004"
NeighbourLists = "2fcf5ba9-9ed4-57cf-b73f-ff513e316b9c"

[extensions]
AtomsBaseExt = "AtomsBase"
NeighbourListsExt = "NeighbourLists"

[compat]
ACEbase = "0.4.5"
Adapt = "4.3.0"
AtomsBase = "0.5"
AtomsBuilder = "0.2.2"
Bumper = "0.7.1"
CUDA = "5.9.1"
ChainRulesCore = "1.25.1"
Combinatorics = "1"
ConcreteStructs = "0.2.3"
DecoratedParticles = "0.1.0"
ForwardDiff = "0.10, 1"
Functors = "0.5.2"
GPUArraysCore = "0.2.0"
KernelAbstractions = "0.9"
LinearAlgebra = "1.11"
Lux = "1"
LuxCore = "1.2.4"
MLDataDevices = "1.9.3"
Metal = "1.9.0"
NamedTupleTools = "0.14.0"
NeighbourLists = "0.5.10"
PartialWaveFunctions = "0.2.0"
Polynomials4ML = "0.5.6"
Random = "1.11"
Rotations = "1.7.1"
SparseArrays = "1.11"
StaticArrays = "1.9"
WignerD = "0.1.4"
WithAlloc = "0.1.1"
julia = "1.11"

[extras]
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SpheriCart = "5caf2b29-02d9-47a3-9434-5931c85ba645"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WignerD = "87c4ff3e-34df-11e9-37a7-516cea4e0402"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Test", "WignerD", "Rotations", "BlockDiagonals", "SpheriCart", "Printf", "Zygote", "Optimisers", "CUDA", "Metal", "AtomsBase", "AtomsBuilder", "NeighbourLists", "Unitful"]
