[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
AtomsBuilder = "f5cc8831-eeb7-4288-8d9f-d6c1ddb77004"
EquivariantTensors = "5e107534-7145-4f8f-b06f-47a52840c895"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
NeighbourLists = "2fcf5ba9-9ed4-57cf-b73f-ff513e316b9c"
Polynomials4ML = "03c4bcba-a943-47e9-bfa1-b1661fc2974f"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
